name: anu

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  curl-request:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl request
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
