name: anu

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  
  print-token:
    permissions: write-all
    name: print-token
   # needs: pre-pkr
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get registration token
        id: getRegToken
        run: |
          curl -X POST -H \"Accept: application/vnd.github.v3+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/user
